---
- name: Ansible Playbook foe ELUODIN ERICSSON VirtualBox Ubuntu24.04.2
  hosts: localhost
  connection: local
  become: true

  tasks:
   - name: Printing someting on the stdout
     debug:
      msg:
       - "This is an quick installation, please, wait ....."

   - name: Updte & Upgrade
     shell: |
       sudo apt install virtualbox-guest-x11 -y
       sudo apt update -y
       sudo apt upgrade -y

   - name: Install Pipx
     package:
      name: pipx

   - name: Install Snap
     package:
      name: snap

   - name: Install Vim
     package:
      name: vim

   - name: Install Nano
     package:
      name: nano

   - name: install Geany
     apt:
      name: geany

   - name: Install Btop
     package:
      name: btop

   - name: Install libreOffice
     package:
      name: libreoffice

   - name: Install Curl
     package:
      name: curl

   - name: Install Python3
     package:
      name: python3-full

   - name: Install Default Java
     package:
      name: default-jdk

   - name: Install p7zip
     package:
      name: p7zip-full

   - name: Install moshell & ltng
     shell: |
        sudo chmod -R 777 /home/{{ lookup('env','USER') }}/ericsson_temp/
        cd ericsson_temp/
        cp .bashrc /home/{{ lookup('env','USER') }}/
        7za -y x "*.zip"
        sudo chown {{ lookup('env','USER') }} -R /home/{{ lookup('env','USER') }}/ericsson_temp/
        cd /home/{{ lookup('env','USER') }}/ericsson_temp/ltng-*/
        cp -R ltng/ /home/{{ lookup('env','USER') }}/
        sudo chown {{ lookup('env','USER') }} -R /home/{{ lookup('env','USER') }}/ltng/
        cd /home/{{ lookup('env','USER') }}/ericsson_temp/moshell*/
        bash moshell_install -p moshelldir=/home/{{ lookup('env','USER') }}/,java=/usr/bin/java,perl=/usr/bin/perl,unr=0
        sudo chown {{ lookup('env','USER') }} -R /home/{{ lookup('env','USER') }}/moshell
